---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'bdrblue'

SiteConfig:
  extensions:
    - LogoExtension

Calendar:
  jquery_included: true
  timezone: Pacific/Auckland
  language: EN

CalendarEvent:
  extensions:
    - AttendanceExtension