---
Name: mysiteroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'AttendanceController//$Action/$ID/$OtherID': 'AttendanceController'
    'SeasonController//$Action/$ID/$OtherID': 'SeasonController'